name: github pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONS_GITHUB_PAT }}
    - name: Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        channel: 'stable'
        cache: true
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build web --web-renderer html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
